---
- name: Update web servers
  hosts: web1.santi.com
  remote_user: vagrant

  tasks:
  - name: Ensure apache is at the latest version
    ansible.builtin.apt:
      name: httpd
      state: latest

  - name: Write the apache config file
    ansible.builtin.template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
